GET http://localhost:8081/api/secrets
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmMTZlMDQ1ZGUyNjFkNGU3OTkzYjNlZiIsIm5hbWUiOiJOZXcgdXNlciIsImlhdCI6MTU5NTMzNDc0MCwiZXhwIjoxNTk1NDIxMTQwfQ.30Czog8g7WANV7MyDGS9PW9fPApWHk1IBV2nGz4p_UE
